### ISSUE TITLE
Why is plane.constant negative?

### ISSUE THREAD

**Issue by Glidias** [Mugen87/yuka#12]
https://github.com/Mugen87/yuka/blob/master/src/math/Plane.js#L102

`this.constant = - point.dot( this.normal );`

There is a minus sign behind. No wonder my simple front/backface test failed vs Polygon. Isn't the standard plane equation offset D always simply the dot product of the normal. Is this a typo?

If you do change it, ensure the following work (if needed):
https://github.com/Mugen87/yuka/search?q=.constant&unscoped_q=.constant

**Comment by Mugen87** [comment]
No, Yuka defines planes in Hessian normal form (analogue to `three.js`).

http://mathworld.wolfram.com/HessianNormalForm.html
