### ISSUE TITLE
Navmesh.clampMovement with Vehicle flocking behaviours

### ISSUE THREAD

**Issue by Glidias** [Mugen87/yuka#13]
I have trouble `Navmesh.clampMovement` to play nicely with a various Vehicle flocking/[path behavious among multiple agents this to work (or maybe it's due to other things). Based on your experience, is this possible? Would be nice to have an example of it.

**Comment by Mugen87** [comment]
> Based on your experience, is this possible?

I've actually not used `Navmesh.clampMovement()` in context of a flocking steering behavior so far. But in general, steering behaviors like flocking or wander can look weird if they are combined with some sort of wall/obstacle avoidance or movement clamping. In certain scenarios, it's better not to just correct the steering force or the final position but give the agent a hint to move in a different direction. 

In this way, the same collision is definitely avoided in the upcoming simulation steps (so the agent does not try to steer over and over again into the same wall).

**Comment by Glidias** [comment]
Yes, I don't just use flocking . I use some constrain to navmesh behaviour like flowfield as well. However, I had to use a seperate collision approach instead of clampMovement because the current one doesn't seem to work too well, and it seems it only checks a single closest edge and may not account for large velocities where multiple potential edges are involved? I don't see any conservative swept aabb or  radius  sphere used in the query for edges

**Comment by Mugen87** [comment]
The idea is to us a spatial index in combination with the nav mesh. It is evaluated in [NavMesh._getClosestBorderEdge()](https://github.com/Mugen87/yuka/blob/0a75ee256fc1b564aa72d9582d9e9d310e22fde8/src/navigation/navmesh/NavMesh.js#L684-L685). In this way, you only check border edges of adjacent regions.

**Comment by Mugen87** [comment]
Closing for now. Feel free to reopen the issue when you can provide more details.
