### ISSUE TITLE
Can I run this in a server?

### ISSUE THREAD

**Issue by jacklaplante** [Mugen87/yuka#14]
I want to add AI controlled enemies to my multiplayer three.js game. How would I go about running this on a server?

**Comment by Mugen87** [comment]
Some context: https://discourse.threejs.org/t/i-need-ideas-on-how-to-add-enemies-in-my-multiplayer-game/11006

Well, Yuka is just a bunch of classes with no rendering dependencies. So you can just include them into a node.js application and implement your game logic. A very basic setup would look like so:

```js
const YUKA = require( 'yuka' );

const entity = new YUKA.GameEntity();

setInterval( () => {

	entity.position.x += 1;

	console.log( 'New position:', entity.position );

}, 1000 );
```
This would update the game entity once per second. However, Yuka does not provide any kind of multiplayer/networking features you would normally find in a game engine. Writing a game server and the respective protocols is very difficult. So this would be a project of its own^^.

If you are interested, I suggest you start with studying how WebRTC and WebSockets work. Maybe you can build something on top of these Web APIs.

**Comment by jacklaplante** [comment]
Ya my current server uses websockets. It's very simple though. It essentially just relays the player's position to all the other players. But if I need to figure out how to represent the world on the server side especially if I want to add AI. I will look into running three.js on the server side. It probably won't be the most efficient solution but at least it would allow some code parity.

**Comment by jacklaplante** [comment]
Actually, if I just use a nav mesh with Yuka could I skip using three entirely?

**Comment by Mugen87** [comment]
> Actually, if I just use a nav mesh with Yuka could I skip using three entirely?

Yes, at least on the server side. I don't think using `three.js` or any other 3D engine is much helpful in addition to Yuka if your focus is just on implementing game logic.

BTW: The API style and math classes are quite similar. If you already know `three.js`, it should be a bit easier to get familiar with Yuka.

**Comment by jacklaplante** [comment]
Hey @Mugen87 I've hit a snag with running Yuka on my node server. I'm getting this error when I try and load a NavMesh.

```
ReferenceError: fetch is not defined
    at Promise (C:\Users\jack\bowdown\server\node_modules\yuka\build\yuka.js:18666:5)
    at new Promise (<anonymous>)
    at NavMeshLoader.load (C:\Users\jack\bowdown\server\node_modules\yuka\build\yuka.js:18664:11)
    at Object.entities.init (C:\Users\jack\bowdown\server\entities.js:15:12)
```

I think Fetch is a browser JS API and doesn't work in node. I'm going to try and see if I can fix this myself (I've never contributed to an open source project and I would like to) But any advice you have would be helpful.

**Comment by Mugen87** [comment]
Try it with this node package:

https://www.npmjs.com/package/node-fetch

We also use it in our unit tests which are executed in a node environment.

**Comment by jacklaplante** [comment]
node-fetch doesn't seem to allow the use of relative urls. So I would have to also set up a local webserver just to server the navmesh. I'm looking into other possible approaches. I'm thinking `fs.readFile` might be my best bet. But that doesn't return a Promise so it would require some rewriting in Yuka

**Comment by Mugen87** [comment]
61f2aaf6499e91c36471dba99fd175c9fc68009a introduced `NavMeshLoader.parse()`. You can now use the API like so:

https://github.com/Mugen87/yuka/blob/e7298300ff2c3b29cd9e983bf9595a44dea9ba03/test/unit_test/navigation/navmesh/NavMeshLoader.tests.js#L158-L170

I hope this makes the class more usable for you 👍

**Comment by jacklaplante** [comment]
I can confirm that this works now, I just needed to reinstall yuka (maybe the version number should be increased)

Thank you @Mugen87 !

**Comment by Mugen87** [comment]
> maybe the version number should be increased

I've actually increased it from `0.1.0` to `0.2.0`.
