### ISSUE TITLE
May I contribute to this project?

### ISSUE THREAD

**Issue by jacklaplante** [Mugen87/yuka#15]
Hey @Mugen87 , how do you feel about my contributing to Yuka? I'm trying to use it for my game but I think it could use some added functionality. How would you feel about me sending you small PR's from time to time?

**Comment by Mugen87** [comment]
Feel free to make PRs, contribution is welcome 😊. Similar to `three.js` and other Open-Source projects, your PRs are going to be reviewed. So I just want to make clear that I can't promise that all of your work are going to be merged 😇.

**Comment by jacklaplante** [comment]
I tried to create a branch to make a PR last night but I didn't have the
proper permissions to create it.

**Comment by Mugen87** [comment]
It seems to work for others: https://github.com/Mugen87/yuka/pull/2. I did not grant the user special permission.  Maybe this helps:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
