### ISSUE TITLE
Is there a certain trick to making a NavMesh

### ISSUE THREAD

**Issue by jacklaplante** [Mugen87/yuka#16]
I'm trying to create a NavMesh from my game map. In Blender, I copied all of the faces I want to be navigable by the Vehicle. Then I export it as a GLTF. Does it matter that the faces are double sided?

**Comment by Mugen87** [comment]
> Does it matter that the faces are double sided?

In many cases, NavMeshes are auto-generated. This process does _not_ output double sided faces. I'm afraid it would not make sense doing this.

**Comment by jacklaplante** [comment]
How do other people generate nav meshes?

**Comment by Mugen87** [comment]
We've done this with Blender 2.7 so far. Unfortunately, the latest Blender version does not support this feature anymore. As a long term goal, we want to introduce a nav mesh generator in Yuka, too.
