### ISSUE TITLE
Maximum call stack size exceeded with `...vertices` spread operator in BVH

### ISSUE THREAD

**Issue by Glidias** [Mugen87/yuka#18]
It happens for a large data set i'm working with.

For the interest of performance/stability, would converting the spread operator line at https://github.com/Mugen87/yuka/blob/master/src/math/BVH.js#L84 to something like `for (let e of vertices) this.root.primitives.push(e); ` suffice? 

possibly related: https://github.com/nodejs/node/issues/16870

**Comment by Mugen87** [comment]
> It happens for a large data set i'm working with.

I'm curious. How many entries do you have in the `vertices` array?

According to the discussion it seems a `for` loop should solve this problem. I'll fix this 👍

**Comment by Mugen87** [comment]
We are using the spread operator at other places, too. But since its syntax is so elegant, I would only provide further patch if you run into the same issue elsewhere.

Fix a505f08d464ca6fa199b67efeb16f59e50a8eb98

**Comment by Glidias** [comment]
How big the data set? I'm not sure if it happens for the first BVH case or the second BVH case.

- 22603 tris , 67809 soup vertices  : Navmesh triangulated polygons
- 44647 tris , 133941 soup vertices : Extruded Navmesh polygons (triangulated) for borders/chamfer corners  of navmesh when  accounting for specific agent radius.

A visual cap (entire land area):
![image](https://user-images.githubusercontent.com/190195/74704761-8c1e2780-524c-11ea-9765-975afe953864.png)
Closup:
![image](https://user-images.githubusercontent.com/190195/74704856-cbe50f00-524c-11ea-9313-f968f1c6d568.png)
