### ISSUE TITLE
Question regarding entities and triggers, etc.

### ISSUE THREAD

**Issue by Glidias** [Mugen87/yuka#21]
Why iterate them backwards in EntityManager?

**Comment by Mugen87** [comment]
The game entity might remove itself from the manager. Normal iteration would break in this use case.

**Comment by Glidias** [comment]
aha simple solution to a typical issue.

**Comment by Mugen87** [comment]
Yeah, the engine does not cover this use case. The convection is: A game entity is allowed to remove itself but no others.
