### ISSUE TITLE
MathUtils.area() misleading

### ISSUE THREAD

**Issue by Glidias** [Mugen87/yuka#25]
I think you left out `*0.5` to the result. For the purpose of Coridoor/Convexity calculations where you just need to check the sign,  understandably this is left out, but as a standalone function, .area() is expected to return some form of "area"?  Then again, the function name itself is misleading because it doesn't clarify whether the "area" is a 2D area vs 3D area . (Based on the method, it's actualy area2DDoubled...)

**Comment by Mugen87** [comment]
The documentation says:

> Computes the signed area of a rectangle defined by three points.

I think this sentence already makes clear what the method does. Moreover

> This method can also be used to calculate the area of a triangle.

We expected that the reader knows how to compute the area of a triangle with the given result.

**Comment by Mugen87** [comment]
Besides, I prefer compact method names. Not a fan of stuff like `thisMethodDoesSomethingVerySpecifc()`. Even if it's descriptive, it's hard to read. The documentation can highlight implementation details.

**Comment by Glidias** [comment]
Oh, it does state "rectangle" within the docs => parallelogram. I guessed i missed out the first sentence.
