### ISSUE TITLE
Clamp Quaternion (Rotation)

### ISSUE THREAD

**Issue by YuryKonvpalto** [Mugen87/yuka#28]
How would you clamp a quaternion (rotation rate on ZorX-axis)? 

We have a plane - XZ-axis, an agent (PursuingBehavior) and an evader. Due to collisions between an agent and an evader (Cannon.js fits very well to Yuka) an evader jump up on Y-axis and an agent tries to follow it - moving on the Y-axis too.
An agent rotates its forward up to position of an evader (direction to target) and then (when the evader falls down on a plane) rotates-dives down (direction to target again).

I've managed to clamp Y-position of an Agent - so it would not go after an evader up - it just waits for it on the plane-Y (0.). I did by simple: IF(agent.position.y >2){agent.position = 2}.
But in meantime an agent rotates around XZ-axis up to lookup to target (evader) and then rotates down when the evader falls.

I've tried to clamp a quaternion of an agent (like Y-position), but erfloglos - no success.
How would you clamp a rotation of an agent betweeen say PI/4 (up) and zero angle of a planeXZ?

![wolfyQuaternion2](https://user-images.githubusercontent.com/64744344/81062211-3fa6c780-8ede-11ea-9d7d-fe117129bed0.png)
![wolfyQuaternion](https://user-images.githubusercontent.com/64744344/81063592-cceb1b80-8ee0-11ea-87f9-3935878d507a.png)

**Comment by Mugen87** [comment]
I'm not sure I fully understand the use case but clamping operations like this might be easier if you have an euler representation of your rotation. Try this approach:
```js
let { x, y, z } = q.toEuler( {} );

// now clamp via MathUtils.clamp()

q.fromEuler( x, y, z );
```

**Comment by YuryKonvpalto** [comment]
Oh, thanks. I thought about conversion from Quat to somthg else, but could not find a right way. Eulers cpuld be a solution. Never tackled with them before though..

**Comment by Mugen87** [comment]
If you google this topic, you will find similar discussion in the Unity forum. Could be a useful resource.
