### ISSUE TITLE
Attach NavMesh from an object that has been loaded

### ISSUE THREAD

**Issue by Coder2012** [Mugen87/yuka#29]
Instead of using NavMeshLoader, is it possible to take my navMesh from my blender scene that I already loaded using GFTL loader?

Also can a NavMesh be updated by adding removing polygons after it has been applied?

**Comment by Mugen87** [comment]
> Instead of using NavMeshLoader, is it possible to take my navMesh from my blender scene that I already loaded using GFTL loader?

Basically yes. You can create a nav mesh from any geometry definition as long as you use `NavMesh.fromPolygons()`. That requires that you convert each face definition to an instance of `Polygon`. You can do this by putting the vertices of a faces (usually three vertices per face) in any array and then use `Polygon().fromContour()`. This approach is used by `NavMeshLoader.parseGeometry()`.

> Also can a NavMesh be updated by adding removing polygons after it has been applied?

No, it's currently not possible to change a navigation mesh after its creation. That would require a new computation of convex regions and the respective navigation graph. So for now, you have to create the nav mesh from scratch if its structure is going to change.
