### ISSUE TITLE
Navmesh appears smaller than it really is

### ISSUE THREAD

**Issue by dc-design** [Mugen87/yuka#30]
I created a simple plane in Blender, removed a couple of faces from it, added triangulate modifier and exported as GLB (tried also with GLTF + bin) but when i load it with NavMeshLoader it appears smaller on screen, without any reason.

Is there any custom property i need to add when i export it?

Here is how it appears:
![Seven 16-5-2020 17-53-16](https://user-images.githubusercontent.com/16717399/82124265-3222f480-979e-11ea-9fd3-2bd0e839ef01.png)

Here are my export settings in Blender:
![Annotazione 2020-05-16 175556](https://user-images.githubusercontent.com/16717399/82124319-96de4f00-979e-11ea-8d74-f8018cf96b2d.png)

**Comment by Mugen87** [comment]
Can you please try apply the transformations of the plane before you export it? You can do this by selecting the object, press <kbd>Ctrl</kbd> + <kbd>A</kbd> and then select `All Transforms`.

http://builder.openhmd.net/blender-hmd-viewport-temp/editors/3dview/object/editing/transform/clear_apply.html#apply

**Comment by dc-design** [comment]
Wonderful! It works!! Thank you man!
