### ISSUE TITLE
Documentation: Add cheat sheet or reference card.

### ISSUE THREAD

**Issue by anonimo82** [Mugen87/yuka#40]
Hello everyone.
I'd like to print the whole class reference for this, is it there any PDF or single page document?

Thanks in advance for any help.

**Comment by Mugen87** [comment]
> is it there any PDF or single page document

Do you mind explaining in more detail how the output would look like? A screenshot of something similar would also be helpful.

I should mentioned that the layout of the documentation is messed up if you try to print a page. There is no support for that and I doubt it makes sense to invest a lot of time in developing printer-optmized styles/CSS.

**Comment by anonimo82** [comment]
Something like this:
![docs](https://user-images.githubusercontent.com/38261009/114520872-2c4dc180-9c42-11eb-9851-9deede626d2f.png)

**Comment by Mugen87** [comment]
Okay, I see now. A cheat sheet or reference card like https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf.

I'm afraid this is currently a bit out of scope since the entire documentation is generated based on JSDoc. Authoring a different documentation that needs additional manual authoring efforts is not something I would support.

However, if somebody could manage to implement a node.js script that could generate such a PDF based the JSDoc, I'm willing to add this to the repository.

**Comment by anonimo82** [comment]
Any update on this?

**Comment by Mugen87** [comment]
No sorry. I've thought about this feature requests multiple time but I'm afraid this won't be implemented since the maintenance effort for a separate documentation resource is just too high. You have to work with the existing documentation.

**Comment by anonimo82** [comment]
This is ok, thanks for (at least) considerimg this.
Cheers =)

**Comment by anonimo82** [comment]
Hey, I did one myself. It's HUGE, but maybe someone can summarise it (?)

[Here it is (for 30 days)](https://easyupload.io/eobrvz)

**Comment by anonimo82** [comment]
@Mugen87 check here

**Comment by anonimo82** [comment]
Sorry for necro posting, but please, I have a different use case now: can we have the whole documentation as pdf or single HTML, printer friendly page?

Thanks in advance for any help. 
Regards, have a nice day.

**Comment by anonimo82** [comment]
Nevermind, I generated the documentation in HTML, then converted each HTML file in PDF with pandoc
`for i in *.html; do pandoc -f html -t pdf -o $i.pdf $i; done`
then joined the PDFs with another package called pdfarranger.

All with Linux, IDK how would I've been done with Windows.... Of course a solution would exist, but IDK it.
If is anyone interested, I can send the final PDF.

Thanks everyone anyhow.
