### ISSUE TITLE
Efficient way to find an intersection

### ISSUE THREAD

**Issue by YuryKonvpalto** [Mugen87/yuka#42]
Hi guys,

what would be a most efficient way to find an intersection between given entities?
Say, we have static entities and a vehicle. Naive approach would be to iterate all entities each worldstep and compare their boundig spheres with a BS of vehicle. But if we have 100 entities it would have an impact on game perfomance.
Is there any variant in Yuka that makes intersection's search more efficient?
I guess may be a Cell division (cell-space partitioning) has smthg to do with it, but not sure...

**Comment by Mugen87** [comment]
> I guess may be a Cell division (cell-space partitioning) has smthg to do with it, but not sure...

Yes, the class [CellSpacePartitioning](https://mugen87.github.io/yuka/docs/CellSpacePartitioning.html) (which is nothing else than a simple spatial index) is the right choice for this use case.

The idea is to divide up the 3D space into cells. You can then determine the so called _neighborhood_ of a game entity. The neighborhood represents a collection of other game entities which are close enough for a potential collision. 

BTW: You don't have to compute the neighborhood by yourself. You can set [GameEntity.updateNeighborhood](https://mugen87.github.io/yuka/docs/GameEntity.html#updateNeighborhood) to `true` so the `EntityManager` automatically computes the closest based on [GameEntity.neighborhoodRadius](https://mugen87.github.io/yuka/docs/GameEntity.html#neighborhoodRadius). You can then access the neighbors by accessing the read-only array property [GameEntity.neighbors](https://mugen87.github.io/yuka/docs/GameEntity.html#neighbors). To speed up this process, assign an instance of `CellSpacePartitioning` and assign it to `EntityManager.spatialIndex`.

**Comment by YuryKonvpalto** [comment]
Thanks a lot for a tip with neighbours! And will dig deep into proposed example (studied it before, but overlooked it uses a CSP).
