### ISSUE TITLE
Yuka and Babylon.js

### ISSUE THREAD

**Issue by eldinor** [Mugen87/yuka#55]
This is actually not an issue, just a question.
Are there any examples of Yuka implementation with Babylon.js?

**Comment by Mugen87** [comment]
No sorry. The official examples all use `three.js`.

Maybe it's a good idea to use BabylonJS at least with one of the simpler steering examples.

**Comment by eldinor** [comment]
Thanks for your answer!
I asked this question because it would save some time for me :)
But if there are no such examples I think I'll begin with some simple ones.

Maybe you already have this example - https://jsfiddle.net/qxmpuojs/ but not for Pixi (which won't work anyway) but for Three.js?

**Comment by Mugen87** [comment]
Updated version of the fiddle: https://jsfiddle.net/e71tmq5j/

I'll try to migrate one of the steering example.

**Comment by Mugen87** [comment]
ddf9c08454cdc112716956d00e0d0df2f6f40a93 should solve this issue.

**Comment by Mugen87** [comment]
Live link: https://mugen87.github.io/yuka/examples/steering/seek/
