### ISSUE TITLE
Question: Best Practices

### ISSUE THREAD

**Issue by arcman77** [Mugen87/yuka#60]
In a given state, one that controls behavior:

Where should changes to the agents steering behavior go?
```
export class FooState extends YUKA.State {
  constructor() {}
  enter(agent) { 
    // Should this go here?
     agent.steering.behaviors[0].active = false
     agent.steering.behvariors[1].active = true
  }
  
  execute(agent) {
      // OR should this go here?
     agent.steering.behaviors[0].active = false
     agent.steering.behvariors[1].active = true
  }
}
```

**Comment by Mugen87** [comment]
Such code is usually placed in `enter()`. `enter()` is executed only once a state becomes active and thus an ideal spot for setting up the game entity (e.g. with new steering behaviors).

**Comment by arcman77** [comment]
Thank you!

**Comment by arcman77** [comment]
A quick follow up question - is there any reason the execute method would not be called after the enter method is called? For the moment that is the behavior that I'm seeing.
