### ISSUE TITLE
Question: NavMesh

### ISSUE THREAD

**Issue by arcman77** [Mugen87/yuka#61]
I have some vehicles that are controlled by steering behaviors, I'm not sure how to combine this with mesh navigation such that the vehicles steering behavior is bounded to the surface of the heightmap mesh I'm using. Is this possible and is it a supported behavior/usecase?

For example, the steering behavior pursuit follow and wander create a force that drives each vehicle, but does that produce a target that I can use the the on path steering behavior with?

From the looks of it, there is a target that I can use to combine with the on path steering?
![image](https://user-images.githubusercontent.com/19784185/164378258-9cef5ec8-56a1-45a8-ad9b-a0c212a3b447.png)

**Comment by Mugen87** [comment]
No steering behavior can ensure that a game entity stays on a navmesh. The follow path and on path behavior (which are normally the steering behaviors that you combine with a navigation mesh) also just follow the navigation path but without any collision detection.

One way to solve this issue is to compute the new position of a game entity per simulation step and then check if this point lies on the navigation mesh. If so, the translation is allowed. If not, the app has to react in _some_ way (e.g. by moving the entity into a different direction).

This kind of approach is used in one of the official showcases to ensure the bots do not leave the leave when dodging the opponent's attacks.

https://github.com/Mugen87/dive/blob/7176136cf6c29eddfd620df2bf0d09a532680763/src/entities/Enemy.js#L777-L795

**Comment by arcman77** [comment]
Thank you. Okay, this ^ is what I started doing. The other approach that I was considering is using the physics engine (ammo.js in my case) to combine resulting forces with those generated by the steering behaviors to arrive at a solution that cannot walk through walls or the ground. 

Pro: This has the advantage of not needing to do a path query at every step of the simulation. 
Con: But this also has the weird effect of the AI traveling paths that are not entirely the result of their driving behaviors and I don't know how that behavior will affect the quality of the steering behavior output.

What do you think?

**Comment by Mugen87** [comment]
TBH, I don't know^^. I've never tried to combine the forces of a physics engine with the steering forces. This might work to a certain extend but could produce weird behaviors if the forces do not match in their scales.

You definitely hit a common problem in game development and even AAA games do not solve this properly in all cases. I guess you try things out until you find a solution that works for your app.

**Comment by arcman77** [comment]
I'll continue testing things out, and if the performance I get is given the approach you suggested is good enough, I think I'll stick with that. I really do appreciate quick feedback. It's hard to make decisions going forward without knowing what the consequences might look like.

**Comment by arcman77** [comment]
Hey so I was wondering if you knew off-hand what the practical performance constraints of the NavMesh class are. For example, if I try to create a NavMesh from this model here:
https://playground.babylonjs.com/#2JBSNA#149
which has 285481 vertices, it seems like to call to load in the nav mesh just never finishes, but the browser does **not** blow up on memory usage either so it's hard for me to say that it's actually a memory/size of mesh issue.

**Comment by arcman77** [comment]
This part of the code:

```
/**
	* Creates the navigation mesh from an array of convex polygons.
	*
	* @param {Array<Polygon>} polygons - An array of convex polygons.
	* @return {NavMesh} A reference to this navigation mesh.
	*/
	fromPolygons( polygons ) {

		this.clear();

		//

		const initialEdgeList = new Array();
		const sortedEdgeList = new Array();

		// setup list with all edges

		for ( let i = 0, l = polygons.length; i < l; i ++ ) {

			const polygon = polygons[ i ];

			let edge = polygon.edge;

			do {

				initialEdgeList.push( edge );

				edge = edge.next;

			} while ( edge !== polygon.edge );

			//

			this.regions.push( polygon );

		}
		
```
		
This part here is what seems to be the hold up. Each iteration through the the for loop take longer than the previous, as the the variable `initialEdgeList` grows in length, the inner while loop takes longer.

**Comment by Mugen87** [comment]
Let's discuss the above issue in the new thread.
