### ISSUE TITLE
Is there any way to add obstacles dynamically on a 2D grid?

### ISSUE THREAD

**Issue by LeCommandeur** [Mugen87/yuka#64]
Hi !

I'm currently working on a small video game where players have to barricade their characters inside a house by putting furnitures along some "open walls" to block the path to prevent ennemies from getting to them.

The main problem is the dynamic nature of the game, we move blocking objects thus we change the valid paths present in the grid.

I have created a 2D grid using `GraphUtils.createGridLayout` and tried two different ways to "update" the graph dynamically.

First, I tried removing nodes in the graph where there are blocking objects but alas, it did not work well, the paths I then got were incorrect and sometimes not even continuous.

Then, I tried to simply update manually the cost of certain nodes' edges so that they would be less likely to be consider better suited for the path. It works but I wonder if there is a better approach?

Could you recommand anything? Is there a special value we can use to make certain nodes "unwalkable"?

Thanks in advance!

**Comment by Mugen87** [comment]
BTW: You could of course change the structure of the grid depending on the terrain but updating edge costs is more flexible. Think of a bridge in a strategy game. If it is destroyed, game entities should not pass it. That can be achieved by assigning a high cost to the respective edge. That means game entities will try to find a way around it. When the bridge is repaired (assuming the game provides such a mechanic), the original edge cost is restored.

**Comment by LeCommandeur** [comment]
Thank you for your quick answer and your advice. I finally manage to achieve what I was looking for, I'm closing the issue!
