### ISSUE TITLE
Building with webpack and es6 modules

### ISSUE THREAD

**Issue by alamboley** [Mugen87/yuka#65]
Hello,

I've a babylon project made with this template https://github.com/RaananW/babylonjs-webpack-es6.

I try to import only what is needed: `import { AStar } from "yuka/src/graph/search/AStar";`  but I get errors:
```
Module not found: Error: Can't resolve 'yuka/src/graph/search/AStar'
```

How to prevent using a global import like: `import { AStar, Graph, GraphUtils, NavEdge } from "yuka";` ?

**Comment by Mugen87** [comment]
TBH, I'm not sure how to do that. I always use rollup for my builds. When using imports like below, the bundler correctly perform treeshaking and includes into the build file what is actually necessary.
```js
import { AStar, Graph, GraphUtils, NavEdge } from "yuka";
```

**Comment by Mugen87** [comment]
Maybe it's because of this line:
https://github.com/Mugen87/yuka/blob/b95f3f0b51d1279d51ace81295d7dd5bd3aca6cc/.npmignore#L4
That will ensure that no `src` directory is present in the `npm` package.

**Comment by alamboley** [comment]
Glad to know it should be done automatically.

Unfortunately, in babylon, I've to precise each path `import { ArcRotateCamera } from "@babylonjs/core/Cameras/arcRotateCamera";` otherwise doing `import { ArcRotateCamera } from "@babylonjs/core";` import the whole package. I can easily check with the output file size. Not sure how to check in the exported bundle if yuka is full or not.

**Comment by Mugen87** [comment]
Try to Import a single class without dependencies like `State`. The bundle should contain no other Yuka classes.

**Comment by alamboley** [comment]
It seems it's ok 👍
