### ISSUE TITLE
SteerBehavior - Vehicle facing the wrong direction

### ISSUE THREAD

**Issue by mikeyriver2** [Mugen87/yuka#71]
Hi! I'm quite new to threejs and 3d stuff in general and I've been experimenting the SteeringBehavior.

I recently purchased a model from sketchfab and basically my goal is to have the model follow the cursor around in a 2d plane. The model seems to be following the target (point of the cursor) just fine, but the model is facing the wrong way. 

Loading the gltf file:
```
let dog;
    const gltfLoader = new GLTFLoader();
    
    gltfLoader.load('./premium_wolf/source/model.gltf', (gltcScene) => {
      dog = gltcScene;
      dog.scene.matrixAutoUpdate = false; 
      vehicle.setRenderComponent(dog.scene, sync);
      scene.add(dog.scene);
    });
```

Applying seek behavior to vehicle/my model:
```
    const seekBehavior = new YUKA.ArriveBehavior(target.position, 2, 1); 
    vehicle.steering.add(seekBehavior);
```

Output:
![Peek 2022-09-22 03-09](https://user-images.githubusercontent.com/47336561/191591376-fea642f3-844c-4a6b-a592-043d5c08f5fc.gif)

Expected Behavior:
- Head should be facing towards the target (and not the butt :p)

Is there a way to rotate the model while the steering behavior is active?

**Comment by Mugen87** [comment]
> Is there a way to rotate the model while the steering behavior is active?

Yes, you have to make sure that the default forward direction of the model is (0,0,1). That means when you load the model and add it to the scene, it should look along the positive z-axis.

Ideally, you fix this in Blender and just import the updated model. If you don't want to do that, transform the model's geometry via `rotateX()`, `rotateY()` or `rotateZ()`(depending on your use case). More information about the geometry API at the [three.js docs](https://threejs.org/docs/index.html#api/en/core/BufferGeometry).

**Comment by Mugen87** [comment]
> using rotation.x or rotateX() did not apply.

Only when you using the `Object3D` interface. When using the methods from `BufferGeometry`, the calculations of Yuka to not intefere.
