### ISSUE TITLE
How to generate NavMesh automatically?

### ISSUE THREAD

**Issue by yangfengzzz** [Mugen87/yuka#72]
I'm just start to learn game AI. Is there any methods in the lib to create NavMesh from a glb automatically? or Is there other tools I should use to create these navmesh?

**Comment by Mugen87** [comment]
Yuka does not yet support automatic navigation mesh generation. 

I have used Blender in the past to generate navigation meshes from the imported geometry. Unfortunately, this feature as well as the entire game engine was deprecated with 2.8. So you have to use a version < 2.8.

If you don't want to fallback to earlier Blender versions, you can still create the navigation mesh's geometry by hand.

**Comment by Mugen87** [comment]
Would be interesting to see if this works 👍 .
