### ISSUE TITLE
NavMeshLoader for Typescript throw reference error for fetch

### ISSUE THREAD

**Issue by NicholasLiang** [Mugen87/yuka#74]
fetch function is not using "node-fetch" when loading navmesh in typescript

unhandledRejection ReferenceError: fetch is not defined
 "node_modules\yuka\build\yuka.js:18962:5"

**Comment by Mugen87** [comment]
Sorry, there is no TypeScript support in this repository. We only focus on JavaScript.

You might want to try to ask your question at Discord: https://discord.gg/MhnFwYM
