### ISSUE TITLE
need explanation for this formula

### ISSUE THREAD

**Issue by mzvast** [Mugen87/yuka#76]
As in this part in [ArriveBehavior](https://mugen87.github.io/yuka/docs/steering_behaviors_ArriveBehavior.js.html#line57). 

```js
70 : 			let speed = distance / deceleration;
71 : 
72 : 			// make sure the speed does not exceed the max
73 : 
74 : 			speed = Math.min( speed, vehicle.maxSpeed );
```

here in line 70 the unit of speed is `m/s`, the unit of distance is `m`, the unit of deceleration is `m/(s^2)`.
So in the aspect of units, left part we get `m/s`, however, right part gives `s^2`, which apparently not equal.

So, am I wrong anywhere? Thanks~

**Comment by Mugen87** [comment]
The computation in line 70 is physically incorrect. It's just an aproximation. `deceleration` is not _meter per second squared_  in this case but just undefined. The idea is to compute a decreased speed with a simple computation.
