### ISSUE TITLE
how to get vehicles to avoid each other?

### ISSUE THREAD

**Issue by clicktodev** [Mugen87/yuka#86]
when multiple enemies are following the player, they start converging on the player location and eventually merge into each other and appear as one.

https://github.com/user-attachments/assets/fafd70f3-97bd-4a09-bcf0-e9a5b5b2e4e9

**Comment by Mugen87** [comment]
You can enforce a so called "non-penetration constraint" very easily based on:

https://github.com/Mugen87/nier/blob/2de52b34e875bac809bce527326d867f569aaf47/src/core/World.js#L1276-L1295

Similar to the method `_enforceNonPenetrationConstraint()`, you iterate through all enemies and call `_checkOverlappingEntites()` with all other enemies. In this way, the enemies will push themselves nicely aside.

The only thing that you have to make sure is that all game entities have proper bounding radius defined.

**Comment by clicktodev** [comment]
@Mugen87 thanks! is it the same implementation to stop the enemies from intersecting with the player in the [arrive](https://mugen87.github.io/yuka/examples/steering/arrive/) behavior?

**Comment by Mugen87** [comment]
Yes, this logic works for player entities as well.

**Comment by clicktodev** [comment]
@Mugen87 i calculated the boundingbox and bounding sphere on my meshes but the bounding radius is always 0.
am i supposed to calculate the bounding radius separately? is it not auto inferred from the render object ?

**Comment by clicktodev** [comment]
@Mugen87  Thanks i got everything working now! I set the bounding radius manually.

What's the best way to dynamically calculate the bounding radius?

**Comment by Mugen87** [comment]
> is it not auto inferred from the render object ? 

No it isn't. You have to set it manually.
