### ISSUE TITLE
How to correctly export a NavMesh from Blender 2.8

### ISSUE THREAD

**Issue by Coder2012** [Mugen87/yuka#9]
I am interested in how the NavMesh example works. I decided to import the mesh into Blender 2.8 (I’m a very proficient Blender user), and after adding a couple of extra triangles to form another poligon I exported this using .gltf + .bin combined.

When loading this back into the demo, I get the following error:

`YUKA.NavMeshLoader: Unable to load navigation mesh. Error: YUKA.NavMeshLoader: Invalid geometry format. Please ensure to represent your geometry as triangles.`

Can anyone share their export settings as there’s quite a few, maybe my export settings are incorrect.

**Comment by Mugen87** [comment]
The error means that your `glTF` asset contains rendering primitives other than `TRIANGLES` (.e.g. `POINTS`, `LINES` etc.).  `NavMeshLoader` makes the assumption that the its geometry data are only defined with triangles.

Can you please share the resulting  `gltf` + `bin` file for debugging? 

BTW: We used to create NavMeshes with Blender < 2.8. The new version has dropped its game engine and thus all NavMesh tools. Another reasons for our plan to write a own custom NavMesh generator in JavaScript.

**Comment by Coder2012** [comment]
Ah so I loaded up 2.7 and saw that there was this navigation mesh creation panel. As you pointed out the game engine has been deprecated in 2.8. 

I created a simple mesh with 3 polys, triangulated it and then exported from 2.8 using the defaults of the Khronos glTF exporter, but I get the same error.

Maybe my understanding of a navmesh is lacking, as long as I have a mesh that co-planar and made of triangles, I'm good to go?

I've attached the export in zip here for you to inspect. 

[navmesh2.zip](https://github.com/Mugen87/yuka/files/3623029/navmesh2.zip)

**Comment by Mugen87** [comment]
This was actually a little bug in `NavMeshLoader` 😇 

Fixed via 426e4dc75d15c2f82f2a02f301096056b3c85b10

> Maybe my understanding of a navmesh is lacking, as long as I have a mesh that co-planar and made of triangles, I'm good to go?

The navmesh does not have to be coplanar as demonstrated by this example: 

https://mugen87.github.io/yuka/examples/navigation/navmeshPerformance/

But yes, a navmesh is made up of triangles and the mesh itself is flat in the sense of it has no volume.

**Comment by oriongunning** [comment]
Hi there, could you guys please tell me why this navmesh does not work?

[lh_dungeon_01.zip](https://github.com/Mugen87/yuka/files/10184880/lh_dungeon_01.zip)

`const data = fs.readFileSync("./public/models/navmesh/lh_dungeon_01.glb"); 
    const loader = new YUKA.NavMeshLoader(); 
    let test = await loader.parse( data.buffer );`

ERROR: 

SyntaxError: Unexpected token ; in JSON at position 12
    at JSON.parse (<anonymous>)
    at NavMeshLoader.parse (D:\xampp\htdocs\orbiter-colyseus\node_modules\yuka\build\yuka.js:19036:22)
    at D:\xampp\htdocs\orbiter-colyseus\src\shared\Utils\loadNavMeshFromFile.ts:7:29
    at Generator.next (<anonymous>)
    at D:\xampp\htdocs\orbiter-colyseus\src\shared\Utils\loadNavMeshFromFile.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (D:\xampp\htdocs\orbiter-colyseus\src\shared\Utils\loadNavMeshFromFile.ts:27:12)
    at loadNavMeshFromFile (D:\xampp\htdocs\orbiter-colyseus\src\shared\Utils\loadNavMeshFromFile.ts:41:12)
    at GameRoom.<anonymous> (D:\xampp\htdocs\orbiter-colyseus\src\server\rooms\GameRoom.ts:32:50)
    at Generator.next (<anonymous>)

**Comment by Mugen87** [comment]
I can load the nav mesh when importing it in the [basic nav mesh demo](https://mugen87.github.io/yuka/examples/navigation/navmesh/). Because of its special geometry, I just had to set the `mergeConvexRegions` option to `false` so the loader does not trigger the merge. It looks like so then:

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/12612165/206438241-83dba8bd-efb3-44f5-969e-62af05fbfcf6.png">

So the nav mesh itself looks fine. Seems there is an issue in your node environment.

**Comment by oriongunning** [comment]
you're right, I've managed to load both in my node.js server and my babylon client, and using the createConvexRegionHelper function to display it, but results looks weird, looks like it's rotated ? Maybe there is something obvious I'm doing wronmg? code is here: https://github.com/oriongunning/t5c
![image](https://user-images.githubusercontent.com/5079492/206879445-aa58ef84-fcec-43ba-82c2-3e2625d02d63.png)

**Comment by Mugen87** [comment]
Try to apply any transformation in Blender to the object and then export again (see http://builder.openhmd.net/blender-hmd-viewport-temp/editors/3dview/object/editing/transform/clear_apply.html#:~:text=To%20apply%20a%20transform%20select,the%20appropriate%20transform%20to%20apply.).

**Comment by oriongunning** [comment]
i have tried rotating in every possible way, doesnt seem to chnage anyhting. the only things that does is the Y+ checbox. when is unticked i cannot go right, when ticked i cannot south... man this is painful. Not your fault @Mugen87 I'm just doing obviously wrong somewhere

**Comment by Mugen87** [comment]
Can you try it with an older Blender version like 2.8?

**Comment by oriongunning** [comment]
Sure, ill give that a try

**Comment by oriongunning** [comment]
same behaviour in 2.8.3

**Comment by oriongunning** [comment]
@Mugen87 hi mate, do those test above help you in any way to identify the issue i'm having on my node server?  (all code is here: https://github.com/oriongunning/t5c/tree/main/src/server)

**Comment by bravebox** [comment]
I have a (I think) simple navmesh but get the same error:

- mesh was initially created with blender 2.79 game engine
- edited mesh in newer version of blender (was experimenting with it)
- it works in three-pathfinding but want get the error with loading model with new NavMeshLoader()
- checked if the mesh is only triangled faces, no other objects

[navmesh.gltf.zip](https://github.com/Mugen87/yuka/files/10419816/navmesh.gltf.zip)

Any help is appreciated! :)
